// GENERATED by scripts/prep-heroe.mjs from the KayKit Adventurers atlases (CC0). Do not edit by hand.
export type Body = 'caballero' | 'barbaro' | 'maga' | 'picaro';
export const ATLAS_GRID = { cols: 8, rows: 4 } as const;
/** Atlas cells [col, row] (row 0 = top of the image) that are clothing / skin, per body. */
export const HERO_PALETTE: Record<Body, { cloth: [number, number][]; skin: [number, number][] }> = {
  caballero: { cloth: [[0, 1]], skin: [[6, 0], [0, 0], [1, 0]] },
  barbaro: { cloth: [[1, 1], [0, 1]], skin: [[6, 0], [0, 0]] },
  maga: { cloth: [[2, 1], [0, 1], [2, 2], [5, 0], [7, 1], [3, 2]], skin: [[7, 2], [0, 0]] },
  picaro: { cloth: [[1, 1], [0, 1], [7, 1], [6, 0], [3, 2]], skin: [[5, 2], [5, 0], [1, 0], [0, 0]] },
};
