/**
 * Every player-facing proper name, in one place so the nephews can rename things.
 * Articles and gender live inside each sentence that uses a name: a rename may need its sentence fixed.
 */
export const NAMES = {
  villain: 'El Marchito',
  heart: 'Corazón del Bosque',
  forestRoot: 'Raíz-madre',
  coastRoot: 'Raíz-madre de la Costa',
  bossForest: 'Tragón de Papel',
  /** Short form used mid-sentence ("al Tragón"). */
  bossForestShort: 'Tragón',
  bossCoast: 'El Antenón',
  eliteForest: 'bruto reforzado',
  eliteCoast: 'bruto escudado',
  powerVine: 'Enredadera',
  powerWind: 'Viento',
  biomeForest: 'el Bosque',
  biomeCoast: 'la Costa',
  gate: 'la Ciénaga',
  deer: 'el Ciervo',
  fish: 'el Pez Grande',
  whale: 'la Ballena',
  pearl: 'perla',
  biomeSwamp: 'el Pantano',
  swampRoot: 'Raíz-madre del Pantano',
  swampGate: 'el Zarzal',
  river: 'la Boca del Río',
  bossSwamp: 'El Zancudo',
  eliteSwamp: 'bruto de turba',
  lieutenant1: 'La Gata Araña',
  powerFire: 'Fuego',
  frog: 'la Rana',
  amber: 'ámbar',
  capa: 'Capa de corteza',
  fogata: 'fogata',
  biomeMountains: 'las Montañas',
  mountainRoot: 'Raíz-madre de la Montaña',
  mountainGate: 'los Peldaños',
  stairs: 'la Escalera del Umbral',
  peak: 'el Pico',
  bossMountain: 'El Cucurucho',
  eliteMountain: 'bruto de roca',
  lieutenant2: 'El Triángulo',
  powerStone: 'Piedra',
  dragon: 'el Dragón',
  dragonWild: 'el Dragón Marchito',
  quartz: 'cuarzo',
  refugio: 'refugio',
  tower: 'torre',
} as const;
